export const login = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    password: "password123",
    role: "Student",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@example.com",
    password: "password456",
    role: "Faculty",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alicejohnson@example.com",
    password: "password789",
    role: "Staff",
  },
  {
    id: 4,
    name: "Robert Brown",
    email: "robertbrown@example.com",
    password: "passwordabc",
    role: "Moderator",
  },
  {
    id: 5,
    name: "Emily Wilson",
    email: "emilywilson@example.com",
    password: "passworddef",
    role: "Student",
  },
  {
    id: 6,
    name: "Michael Lee",
    email: "michaellee@example.com",
    password: "passwordghi",
    role: "Faculty",
  },
  {
    id: 7,
    name: "Sophia Taylor",
    email: "sophiataylor@example.com",
    password: "passwordjkl",
    role: "Staff",
  },
  {
    id: 8,
    name: "Daniel Clark",
    email: "danielclark@example.com",
    password: "passwordmno",
    role: "Moderator",
  },
  {
    id: 9,
    name: "Olivia White",
    email: "oliviawhite@example.com",
    password: "passwordpqr",
    role: "Administrator",
  },
  {
    id: 10,
    name: "Ethan Brown",
    email: "ethanbrown@example.com",
    password: "passwordstu",
    role: "Administrator",
  },
];
